name: Trigger auto deployment for interview-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Antra_Projects/HRM/Interviews/**'
    - '.github/workflows/interview-container-AutoDeployTrigger-413f84e3-d5e3-465c-914a-765fd8b03720.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.INTERVIEWCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Antra_Projects/HRM/Interviews 
          registryUrl: fullstackbatchcr.azurecr.io
          registryUsername: ${{ secrets.INTERVIEWCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INTERVIEWCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: interview-container
          resourceGroup: FullStackBatch
          imageToBuild: fullstackbatchcr.azurecr.io/interview-container:${{ github.sha }}
          dockerfilePath: Dockerfile

     

